services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devis_factures_db
      POSTGRES_USER: django_user_admin
      POSTGRES_PASSWORD: qwerty12345
    ports:
      - "5432:5432"

  web:
    build: .
    command: sleep infinity
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://django_user_admin:qwerty12345@db:5432/devis_factures_db
    depends_on:
      - db

volumes:
  postgres_data: