# Generated by Django 5.0 on 2026-03-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facture',
            new_name='Invoice',
        ),
        migrations.RenameModel(
            old_name='HistoriqueFacture',
            new_name='InvoiceHistory',
        ),
        migrations.RenameModel(
            old_name='LigneFacture',
            new_name='InvoiceLine',
        ),
    ]
