# Generated by Django 5.0 on 2026-03-05 12:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('unit_price_excl_tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT')),
                ('unit', models.CharField(choices=[('heure', 'Hour'), ('jour', 'Day'), ('forfait', 'Flat rate')], max_length=20, verbose_name='Unité')),
                ('taux_tva', models.DecimalField(choices=[(Decimal('20.00'), '20%'), (Decimal('10.00'), '10%'), (Decimal('5.50'), '5.5%'), (Decimal('0.00'), '0%')], decimal_places=2, max_digits=4, verbose_name='Taux TVA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services_prestation',
            },
        ),
    ]
