# Generated by Django 5.0 on 2026-03-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adresse',
            new_name='Address',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['id'],
            },
        ),
    ]
