# Generated by Django 5.0 on 2026-02-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfiguration',
            name='invoice_prefix',
            field=models.CharField(default='FAC', max_length=10, verbose_name='Préfixe facture'),
        ),
        migrations.AlterField(
            model_name='userconfiguration',
            name='quote_prefix',
            field=models.CharField(default='DEV', max_length=10, verbose_name='Préfixe devis'),
        ),
    ]
