# Generated by Django 5.0 on 2026-03-05 09:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('numero', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro')),
                ('date_emission', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('date_validite', models.DateField(blank=True, null=True, verbose_name='Date de validité')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('EXPIRE', 'Expiré')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('objet', models.CharField(blank=True, max_length=255, verbose_name='Objet')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total TTC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='clients.client', verbose_name='Client')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'db_table': 'devis',
                'ordering': ['-date_emission', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('ancien_statut', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(max_length=20, verbose_name='Nouveau statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='quotes.devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Historique de devis',
                'verbose_name_plural': 'Historiques de devis',
                'db_table': 'historique_devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Quantité')),
                ('unite', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='quotes.devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'db_table': 'lignes_devis',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
