# Generated by Django 5.0 on 2026-03-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devis',
            new_name='Quote',
        ),
        migrations.RenameModel(
            old_name='HistoriqueDevis',
            new_name='QuoteHistory',
        ),
        migrations.RenameModel(
            old_name='LigneDevis',
            new_name='QuoteLine',
        ),
    ]
